
import java.awt.*;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Andri-Dhika
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        cekmenu();
        setupDatabase();
        try {
            tf.setListLapangan(db.loadLapangan());
            tf.setListMember(db.loadMember());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        refreshLapangan();
        resetMember();
    }

    public void setupDatabase() {
        FileIO fileIO = new FileIO();
        try {
            boolean valid = true;
            String[] dbSetup = fileIO.loadDatabaseSetup();
            for (String dbSetup1 : dbSetup) {
                if (dbSetup1.isEmpty()) {
                    valid = false;
                    break;
                }
            }
            if (!valid) {
                throw new IllegalArgumentException("Setup Database Belum Terisi. Silahkan Edit File Database Setup.txt");
            }
            db = new Database(dbSetup[0], dbSetup[1], dbSetup[2]);
            db.connect();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private Orang OrangAktif = null;
    private Database db;
    private TempatFutsal tf = new TempatFutsal("Tempat Futsal Seger", "I-53");

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogLogin = new javax.swing.JDialog();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLoginPopUp = new javax.swing.JButton();
        grup = new javax.swing.ButtonGroup();
        Utama = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLapangan = new javax.swing.JTable();
        jButtonPesanBatal = new javax.swing.JButton();
        Admin = new javax.swing.JPanel();
        KelolaLapangan = new javax.swing.JPanel();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        KelolaMember = new javax.swing.JPanel();
        fieldUsenameMember = new javax.swing.JTextField();
        fieldPasswordMember = new javax.swing.JTextField();
        fieldNamaMember = new javax.swing.JTextField();
        fieldUmurMember = new javax.swing.JSpinner();
        btnAddMember = new javax.swing.JButton();
        btnEditMember = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableMember = new javax.swing.JTable();
        btnCancelMember = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnSearchMember = new javax.swing.JButton();
        KelolaJadwal = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Tersedia = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Toolbar = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnLapangan = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();

        DialogLogin.setTitle("Login\n");

        jLabel3.setText("Username");

        jLabel10.setText("Password");

        btnLoginPopUp.setText("Login");
        btnLoginPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPopUpActionPerformed(evt);
            }
        });
        btnLoginPopUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginPopUpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout DialogLoginLayout = new javax.swing.GroupLayout(DialogLogin.getContentPane());
        DialogLogin.getContentPane().setLayout(DialogLoginLayout);
        DialogLoginLayout.setHorizontalGroup(
            DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLoginLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoginPopUp)
                    .addGroup(DialogLoginLayout.createSequentialGroup()
                        .addGroup(DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(fieldUsername))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        DialogLoginLayout.setVerticalGroup(
            DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLoginLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(btnLoginPopUp)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Utama.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        TabelLapangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelLapangan.setColumnSelectionAllowed(true);
        TabelLapangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelLapanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelLapangan);

        jButtonPesanBatal.setText("Pesan");
        jButtonPesanBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesanBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesanBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesanBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Utama.add(Home, "card2");

        Admin.setLayout(new java.awt.CardLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setText("Panjang");

        jLabel2.setText("Lebar");

        jLabel8.setText("Harga");

        jButton6.setText("Add");

        jButton7.setText("Edit");

        jButton8.setText("Cancel");

        jButton9.setText("Delete");

        javax.swing.GroupLayout KelolaLapanganLayout = new javax.swing.GroupLayout(KelolaLapangan);
        KelolaLapangan.setLayout(KelolaLapanganLayout);
        KelolaLapanganLayout.setHorizontalGroup(
            KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelolaLapanganLayout.createSequentialGroup()
                .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelolaLapanganLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaLapanganLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(KelolaLapanganLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(KelolaLapanganLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        KelolaLapanganLayout.setVerticalGroup(
            KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelolaLapanganLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KelolaLapanganLayout.createSequentialGroup()
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(107, 107, 107)
                        .addGroup(KelolaLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton7)
                            .addComponent(jButton6))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Admin.add(KelolaLapangan, "card3");

        btnAddMember.setText("Add");
        btnAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemberActionPerformed(evt);
            }
        });

        btnEditMember.setText("Edit");
        btnEditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMemberActionPerformed(evt);
            }
        });

        btnDeleteMember.setText("Delete");
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });

        TableMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMemberMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableMember);

        btnCancelMember.setText("Cancel");
        btnCancelMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelMemberActionPerformed(evt);
            }
        });

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Nama");

        jLabel7.setText("Umur");

        btnSearchMember.setText("Search");

        javax.swing.GroupLayout KelolaMemberLayout = new javax.swing.GroupLayout(KelolaMember);
        KelolaMember.setLayout(KelolaMemberLayout);
        KelolaMemberLayout.setHorizontalGroup(
            KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaMemberLayout.createSequentialGroup()
                .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KelolaMemberLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelMember))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KelolaMemberLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldUsenameMember, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPasswordMember, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldUmurMember, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelolaMemberLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchMember))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                .addContainerGap())
        );
        KelolaMemberLayout.setVerticalGroup(
            KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldUsenameMember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMember))
                .addGap(6, 6, 6)
                .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelolaMemberLayout.createSequentialGroup()
                        .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPasswordMember, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(fieldUmurMember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(KelolaMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddMember)
                            .addComponent(btnEditMember)
                            .addComponent(btnDeleteMember)
                            .addComponent(btnCancelMember)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        Admin.add(KelolaMember, "card2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Vinyl", "Sintetis" }));

        jLabel9.setText("Lapangan");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        grup.add(Tersedia);
        Tersedia.setText("Tersedia");

        grup.add(jRadioButton1);
        jRadioButton1.setText("Booking");

        grup.add(jRadioButton2);
        jRadioButton2.setText("Sudah DP");

        jLabel11.setText("Status");

        jButton10.setText("Add");

        jButton11.setText("Edit");

        jButton12.setText("Delete");

        javax.swing.GroupLayout KelolaJadwalLayout = new javax.swing.GroupLayout(KelolaJadwal);
        KelolaJadwal.setLayout(KelolaJadwalLayout);
        KelolaJadwalLayout.setHorizontalGroup(
            KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelolaJadwalLayout.createSequentialGroup()
                .addGroup(KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelolaJadwalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KelolaJadwalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12))
                    .addGroup(KelolaJadwalLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(Tersedia)
                            .addComponent(jRadioButton2))))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        KelolaJadwalLayout.setVerticalGroup(
            KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelolaJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaJadwalLayout.createSequentialGroup()
                        .addGroup(KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(Tersedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(84, 84, 84)
                        .addGroup(KelolaJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addComponent(jButton12))
                        .addGap(119, 119, 119))
                    .addGroup(KelolaJadwalLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        Admin.add(KelolaJadwal, "card4");

        Utama.add(Admin, "card4");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnMember.setText("Member");
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });

        btnLapangan.setText("Lapangan");
        btnLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapanganActionPerformed(evt);
            }
        });

        btnJadwal.setText("Jadwal");
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });

        Label1.setText("Welcome ,");

        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLapangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJadwal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHome)
                        .addComponent(btnMember)
                        .addComponent(btnLapangan)
                        .addComponent(btnJadwal))
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Utama, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loginMember(String username, String password) throws SQLException{
        int i = tf.searchMember(username);
        if (i >= 0){
            Member m = tf.getMember(i);
            if(m.getPassword().equals(db.encryptPassword(password))){
                OrangAktif = m;
            }
        }
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (btnLogin.getText().equals("Login")) {
            DialogLogin.setSize(400, 275);
            DialogLogin.setVisible(true);
        } else {
            OrangAktif = null;
        }
        cekmenu();


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        Home.setVisible(true);
        Admin.setVisible(false);

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Admin.setVisible(true);
        KelolaLapangan.setVisible(false);
        KelolaMember.setVisible(true);
        KelolaJadwal.setVisible(false);
        refreshMember();
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapanganActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Admin.setVisible(true);
        KelolaLapangan.setVisible(true);
        KelolaMember.setVisible(false);
        KelolaJadwal.setVisible(false);
    }//GEN-LAST:event_btnLapanganActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Admin.setVisible(true);
        KelolaLapangan.setVisible(false);
        KelolaMember.setVisible(false);
        KelolaJadwal.setVisible(true);
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnLoginPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPopUpActionPerformed
        // TODO add your handling code here:
        if (fieldUsername.getText().equals("admin") && fieldPassword.getText().equals("admin")) {
            OrangAktif = new Admin("Admin", 99);
            cekmenu();
            Label1.setVisible(true);
            labelUsername.setVisible(true);
            labelUsername.setText("Admin");
        } else {
            try {
                loginMember(fieldUsername.getText(),fieldPassword.getText());
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            Label1.setVisible(true);
            labelUsername.setVisible(true);
            labelUsername.setText(fieldUsername.getText());
        }
        DialogLogin.setVisible(false);
        fieldUsername.setText(null);
        fieldPassword.setText(null);
        if (OrangAktif == null) {
            JOptionPane.showMessageDialog(rootPane, "Username / Password tidak sesuai");
        }
        cekmenu();

    }//GEN-LAST:event_btnLoginPopUpActionPerformed

    private void btnLoginPopUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginPopUpKeyPressed
        // TODO add your handling code he
    }//GEN-LAST:event_btnLoginPopUpKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TabelLapanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelLapanganMouseClicked
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(rootPane, "Anda Memilih " + (TabelLapangan.getSelectedColumn()-1) + " " + TabelLapangan.getSelectedRow());
        int hari = TabelLapangan.getSelectedColumn()-1;
        if (hari > 0){
            Lapangan lapanganTerpilih = tf.getLapangan(jComboBox1.getSelectedIndex());
            int shift = TabelLapangan.getSelectedRow();
            if (OrangAktif == null){
                jButtonPesanBatal.setVisible(false);
            } else if (lapanganTerpilih.getJadwal(hari, shift).getPenyewa() == null) {
                jButtonPesanBatal.setText("Pesan");
                jButtonPesanBatal.setVisible(true);
            } else if ((lapanganTerpilih.getJadwal(hari, shift).getPenyewa().equals(OrangAktif)) ){
                jButtonPesanBatal.setText("Batal");
                jButtonPesanBatal.setVisible(true);
            } 
        }
    }//GEN-LAST:event_TabelLapanganMouseClicked

    private void jButtonPesanBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesanBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesanBatalActionPerformed

    private void btnAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemberActionPerformed
        // TODO add your handling code here:
        Member m = new Member(fieldUsenameMember.getText(),fieldPasswordMember.getText(),fieldNamaMember.getText(),(int)fieldUmurMember.getValue());
        try {
            db.addMember(m);
            tf.setListMember(db.loadMember());
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        fieldUsenameMember.setText("");
        fieldPasswordMember.setText("");
        fieldNamaMember.setText("");
        fieldUmurMember.setValue(0);
        refreshMember();
        
    }//GEN-LAST:event_btnAddMemberActionPerformed

    private void TableMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMemberMouseClicked
        // TODO add your handling code here:
        Member m = tf.getMember(TableMember.getSelectedRow());
        fieldUsenameMember.setText(m.getUsername());
        fieldPasswordMember.setEnabled(false);
        fieldPasswordMember.setText(m.getPassword());
        fieldNamaMember.setText(m.getNama());
        fieldUmurMember.setValue(m.getUmur());
        btnEditMember.setVisible(true);
        btnDeleteMember.setVisible(true);
        btnAddMember.setVisible(false);
    }//GEN-LAST:event_TableMemberMouseClicked

    private void btnCancelMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelMemberActionPerformed
        // TODO add your handling code here:
        resetMember();
    }//GEN-LAST:event_btnCancelMemberActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        // TODO add your handling code here:
        Member m = tf.getMember(TableMember.getSelectedRow());
        try {
            db.deleteMember(m);
            tf.setListMember(db.loadMember());
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetMember();
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void btnEditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMemberActionPerformed
        // TODO add your handling code here:
        Member m = tf.getMember(TableMember.getSelectedRow());
        m.setUsername(fieldUsenameMember.getText());
        m.setUmur((int)fieldUmurMember.getValue());
        m.setNama(fieldNamaMember.getText());
        try {
            db.editMember(m);
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetMember();
    }//GEN-LAST:event_btnEditMemberActionPerformed

    public void refreshLapangan() {
        jComboBox1.removeAllItems();
                for (int i = 0; i < tf.getJumlahLapangan(); i++) {
            jComboBox1.addItem(tf.getLapangan(i).toString());
        }
    }

    public void refreshJadwalLapangan(int indexLapangan) {
        String[] title = {"Jam\\Hari", "Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu"};
        String[][] data = new String[17][title.length];
        Lapangan lap = tf.getLapangan(indexLapangan);
        for (int i = 0; i < 17; i++) {
            String shift = (i + 7) + ".00";
            data[i][0] = shift;
            for (int j = 0; j < 7; j++) {
                data[i][j+1] = lap.getJadwal(j, i).toString();
            }
        }
        TabelLapangan.setModel(new DefaultTableModel(data, title));
    }
    
    public void refreshMember(){
        String[] title = { "Username","Nama","Umur"};
        String[][] data = new String[tf.getJumlahMember()][title.length];
        for (int i = 0; i < tf.getJumlahMember(); i++) {
            data[i][0] = tf.getMember(i).getUsername();
            data[i][1] = tf.getMember(i).getNama();
            data[i][2] = tf.getMember(i).getUmur()+ "";
        }
        TableMember.setModel(new DefaultTableModel(data, title));
    }
    
    public void resetMember(){
        btnAddMember.setVisible(true);
        btnEditMember.setVisible(false);
        btnDeleteMember.setVisible(false);
        fieldUsenameMember.setText("");
        fieldPasswordMember.setText("");
        fieldNamaMember.setText("");
        fieldUmurMember.setValue(0);
        TableMember.clearSelection();
        refreshMember();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI g = new GUI();
                g.setVisible(true);
                g.setTitle("Aplikasi Pemesanan Lapangan Futsal");

            }
        });
    }

    public void cekmenu() {
        Home.setVisible(true);
        if (OrangAktif == null) {
            btnLogin.setText("Login");
            Label1.setVisible(false);
            labelUsername.setVisible(false);
        } else {
            btnLogin.setText("Logout");
        }
        if (OrangAktif == null) {
            jButtonPesanBatal.setVisible(false);
            btnMember.setVisible(false);
            btnLapangan.setVisible(false);
            btnJadwal.setVisible(false);
            Admin.setVisible(false);
        } else if (OrangAktif.getStatus().equals("Admin")) {
            jButtonPesanBatal.setVisible(false);
            Home.setVisible(false);
            btnMember.setVisible(true);
            btnLapangan.setVisible(true);
            btnJadwal.setVisible(true);
            Admin.setVisible(true);
        } else if (OrangAktif.getStatus().equals("Member")) {
            jButtonPesanBatal.setVisible(true);
            Home.setVisible(false);
            btnMember.setVisible(false);
            btnLapangan.setVisible(false);
            btnJadwal.setVisible(true);
            Admin.setVisible(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JDialog DialogLogin;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel KelolaJadwal;
    private javax.swing.JPanel KelolaLapangan;
    private javax.swing.JPanel KelolaMember;
    private javax.swing.JLabel Label1;
    private javax.swing.JTable TabelLapangan;
    private javax.swing.JTable TableMember;
    private javax.swing.JRadioButton Tersedia;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JPanel Utama;
    private javax.swing.JButton btnAddMember;
    private javax.swing.JButton btnCancelMember;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnEditMember;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnLapangan;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginPopUp;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnSearchMember;
    private javax.swing.JTextField fieldNamaMember;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldPasswordMember;
    private javax.swing.JSpinner fieldUmurMember;
    private javax.swing.JTextField fieldUsenameMember;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.ButtonGroup grup;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonPesanBatal;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
